ALTER TABLE customer_notifications
    MODIFY COLUMN message_type ENUM(
    'REGISTRATION_RECEIVED',
    'TECHNICAL_SURVEY_RESULT',
    'CONTRACT_READY_TO_SIGN',
    'CONTRACT_ACTIVATED',
    'INSTALLATION_INVOICE_ISSUED',
    'WATER_BILL_ISSUED',
    'SERVICE_INVOICE_ISSUED',
    'PAYMENT_REMINDER',
    'CONTRACT_EXPIRY_REMINDER',
    'LEAK_WARNING',
    'INVOICE_PAYMENT_SUCCESS',
    'LATE_PAYMENT_NOTICE',
    'GENERAL',
    'ACCOUNT_CREATED'
    );